### Numpy 2

In [2]:
import numpy as np

In [8]:
sayi_listesi=np.random.randint(0,101,20)

In [10]:
sayi_listesi

array([ 97,  25,  16,  91,  31,  82,  25,  67,  22,  95, 100,  23,  13,
        54,  97,  66,  59,  25,  87,  36])

In [12]:
#sayı listesini sıralama
sayi_listesi=np.sort(sayi_listesi)
sayi_listesi

array([ 13,  16,  22,  23,  25,  25,  25,  31,  36,  54,  59,  66,  67,
        82,  87,  91,  95,  97,  97, 100])

In [14]:
isim='Ceren'
isim[::-1]

'nereC'

In [22]:
sayi_listesi2=np.sort(sayi_listesi)[::-1]
sayi_listesi2

array([100,  97,  97,  95,  91,  87,  82,  67,  66,  59,  54,  36,  31,
        25,  25,  25,  23,  22,  16,  13])

In [36]:
sayi_listesi3=np.arange(0,10) #arange metoduyla liste oluşturma

In [38]:
sayi_listesi3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.flipud(sayi_listesi3)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
sayi_listesi3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#help foksiyonu
help(np.maximum)

In [44]:
np.maximum([100,50,30],[20,80,30])

array([100,  80,  30])

In [46]:
liste1=[100,50,30]
liste2=[20,80,30]
np.maximum(liste1,liste2)

array([100,  80,  30])

In [50]:
np.maximum(20,50) #ikili arama algoritmalarında yararlı

50

In [52]:
#dizileri yeniden şekillendirme
sayi_listesi=np.random.randint(0,101,20)
sayi_listesi.ndim

1

In [64]:
sayi_listesi

array([89, 97, 36, 57, 83, 56, 64, 76, 87, 36, 94, 23, 10, 11, 36, 52, 50,
       36, 64, 46])

In [66]:
sayi_listesi.shape

(20,)

In [56]:
#2 boyut için x,y eksenleri 4*5
sayi_listesi2d=sayi_listesi.reshape(4,5)

In [58]:
sayi_listesi2d

array([[89, 97, 36, 57, 83],
       [56, 64, 76, 87, 36],
       [94, 23, 10, 11, 36],
       [52, 50, 36, 64, 46]])

In [62]:
sayi_listesi2d.shape

(4, 5)

In [82]:
#eğer azaltmak istiyorsak -1 dememiz gerekir, ya da (sayı,boşluk) yazmamız gerekir.
sayi_listesi1d=sayi_listesi2d.reshape(-1) 
sayi_listesi1d

array([89, 97, 36, 57, 83, 56, 64, 76, 87, 36, 94, 23, 10, 11, 36, 52, 50,
       36, 64, 46])

In [84]:
sayi_listesi1d.shape

(20,)

In [86]:
sayi_listesi1d.ndim

1

In [90]:
len(sayi_listesi2d)

4

In [94]:
#Renkler
renkler=np.array(['kırmızı', 'yeşil', 'mavi', 'beyaz'])
renkler[-3]

'yeşil'

In [96]:
ana_renkler=np.array(['kırmızı', 'yeşil', 'mavi'])
ara_renkler=np.array(['turuncu', 'mor', 'sarı'])
#renkleri birleştir
renkler=np.concatenate((ana_renkler, ara_renkler))
renkler

array(['kırmızı', 'yeşil', 'mavi', 'turuncu', 'mor', 'sarı'], dtype='<U7')

In [100]:
renkler2=np.array([ana_renkler, ara_renkler])
renkler2

array([['kırmızı', 'yeşil', 'mavi'],
       ['turuncu', 'mor', 'sarı']], dtype='<U7')

In [247]:
ogrenci1=np.array(['Ceren','K','26'])
ogrenci2=np.array(['Murat','E','42'])
ogrenciler=np.array([ogrenci1,ogrenci2])
ogrenciler

array([['Ceren', 'K', '26'],
       ['Murat', 'E', '42']], dtype='<U5')

In [209]:
ogrenciler[0] #indexi 1 olan öğrenci

array(['Ceren', 'K', '26'], dtype='<U5')

In [114]:
ogrenciler[0][1] #satır sütun

'K'

In [116]:
type(ogrenciler[1][0])

numpy.str_

In [118]:
ogrenciler[1][2]

'42'

In [213]:
ogrenciler[0:1]

array([['Ceren', 'K', '26']], dtype='<U5')

### bir matrisyen isim ve yaşı almak

In [261]:
isim_yas=ogrenciler[:,[0,2]] #sadece belirli bir kısmı görmek istiyorsak o kısmın rakamlarını yazmalıyız ama hepsini görmek istiyorsak 0,1,2 üçlü şekilde yazmalıyız 

In [263]:
isim_yas

array([['Ceren', '26'],
       ['Murat', '42']], dtype='<U5')

In [155]:
ogrenciler[:,[0]]

array([['Ceren'],
       ['Murat']], dtype='<U5')

In [157]:
#copy metodu, diziyi kopyalamaya yardımcı olur
array1=np.array([1,2,3,4,5])
array2=array1.copy()
array2[1]=20
array1,array2

(array([1, 2, 3, 4, 5]), array([ 1, 20,  3,  4,  5]))

In [ ]:
#view metodu, copy aslını değiştirmez ama view değiştirir.


In [159]:
array1=np.array([1,2,3,4,5])
array2=array1.view()
array2[1]=20
array1,array2

(array([ 1, 20,  3,  4,  5]), array([ 1, 20,  3,  4,  5]))

In [163]:
vize_puan=np.random.randint(50,101,20)
vize_puan

array([90, 91, 73, 96, 51, 79, 97, 91, 68, 85, 55, 56, 71, 94, 67, 70, 70,
       83, 84, 55])

In [165]:
#dosyayı kaydetmek istersek
np.savetxt('notlar.txt', vize_puan)

In [3]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 4C16-0290

 Directory of C:\Users\gulcy\Documents\Bootcamp\day6

09.08.2024  23:46    <DIR>          .
09.08.2024  21:34    <DIR>          ..
09.08.2024  22:39    <DIR>          .ipynb_checkpoints
09.08.2024  22:17               520 notlar.txt
09.08.2024  23:46            30.929 Numpy2.ipynb
               2 File(s)         31.449 bytes
               3 Dir(s)  399.895.203.840 bytes free


In [175]:
vize_puanlar=np.loadtxt('notlar.txt')

In [179]:
print(*vize_puanlar)

90.0 91.0 73.0 96.0 51.0 79.0 97.0 91.0 68.0 85.0 55.0 56.0 71.0 94.0 67.0 70.0 70.0 83.0 84.0 55.0


In [181]:
np.sort(vize_puanlar)

array([51., 55., 55., 56., 67., 68., 70., 70., 71., 73., 79., 83., 84.,
       85., 90., 91., 91., 94., 96., 97.])

In [ ]:
#betimsel istatistikler

In [183]:
#mean-ortalama
np.mean(vize_puanlar)

76.3

In [185]:
#ortanca median
np.median(vize_puanlar)

76.0

In [193]:
#standart sapma
np.std(vize_puanlar)

14.439875345722344

In [195]:
#varyans sd**2, standart sapmanın karesidir. Dağılım hakkında bilgi verir
np.var(vize_puanlar)

208.51

In [197]:
#minimum ve maximum
np.amax(vize_puanlar)

97.0

In [199]:
np.amin(vize_puanlar)

51.0

In [203]:
outlier_max=np.mean(vize_puanlar)+3*np.std(vize_puanlar)
outlier_max

119.61962603716702

In [207]:
outlier_min=np.mean(vize_puanlar)-3*np.std(vize_puanlar)
outlier_min

32.980373962832964

In [275]:
puanlar=np.random.normal(loc=75,scale=10,size=21) #ortalama 75,std=10 21 tane not
puanlar

array([79.46178283, 71.27239578, 75.94892142, 81.56279825, 77.00532885,
       76.89177114, 77.27305824, 90.47311634, 67.34235349, 72.59122625,
       69.02882048, 83.08775002, 81.66599893, 92.95518111, 69.43819453,
       81.99630455, 90.63339667, 75.19740031, 82.28538461, 60.71196994,
       71.74126009])

In [293]:
puanlar_int=np.rint(puanlar).astype(int) #round int/tam sayı olarak tuvarla .0 şeklinde duran ondalıklı kısmı iste astype ile çevir
puanlar_int

array([79, 71, 76, 82, 77, 77, 77, 90, 67, 73, 69, 83, 82, 93, 69, 82, 91,
       75, 82, 61, 72])

In [295]:
np.rint(puanlar)

array([79., 71., 76., 82., 77., 77., 77., 90., 67., 73., 69., 83., 82.,
       93., 69., 82., 91., 75., 82., 61., 72.])

In [297]:
np.mean(puanlar)

77.55068637295186

In [299]:
np.median(puanlar)

77.00532885386853

In [301]:
np.std(puanlar)

7.921736482292793

In [307]:
ogrenci_puanları=puanlar_int.reshape(7,3) #vize, final ve derse devam puanları
ogrenci_puanları

array([[79, 71, 76],
       [82, 77, 77],
       [77, 90, 67],
       [73, 69, 83],
       [82, 93, 69],
       [82, 91, 75],
       [82, 61, 72]])

In [311]:
#Sütunlardaki en yüksek puanlar
np.amax(ogrenci_puanları, axis=0)

array([82, 93, 83])

In [319]:
#satırlar bazında en yüksek puan, her 1 satır 1 öğrencinin verisine denk geliyor.
np.amax(ogrenci_puanları, axis=1) #öğrencinin tüm sınavlardan aldığı en yüksek puanları verir

array([79, 82, 90, 83, 93, 91, 82])

In [335]:
np.random.seed(42) #random state42, rastgele diziler içinde belirli bir diziyi seçer.
notlar1=np.random.normal(loc=50,scale=5,size=20)
notlar1=np.rint(notlar1).astype(int)
print(notlar1)
notlar2=.7*notlar1*np.random.normal(loc=0,scale=5,size=20)
notlar2=np.rint(notlar2).astype(int)
print(notlar2)
corr=np.corrcoef(notlar1,notlar2)
corr

[52 49 53 58 49 49 58 54 48 53 48 48 51 40 41 47 45 52 45 43]
[ 267  -39   13 -289  -93   19 -234   71 -101  -54 -101  311   -2 -148
  118 -201   33 -357 -209   30]


array([[ 1.        , -0.21653418],
       [-0.21653418,  1.        ]])

In [343]:
hava_sıcaklıkları=np.array([30,40,35,45,32,30,38])
dondurma_tüketimi=np.array([4500,6000,5250,6800,4700,4500,5900])
np.corrcoef(hava_sıcaklıkları, dondurma_tüketimi)


array([[1.        , 0.99568558],
       [0.99568558, 1.        ]])

In [ ]:
#hava sıcaklıkları ile ısıtıcı satışlarının negatif yönlü korelasyondur.
#alım gücü ve enflasyon da negatif yönlü korelasyondur.
#sigara tüketimi ve sağlık
#uyku süresi ve stres 

In [346]:
memleket=np.array(['Ankara','Antalya','Ankara','Antalya', 'İzmir',
          'İstanbul','İstanbul','İstanbul','İstanbul'])

In [348]:
#Çoklu varsa eğer tek tek yazdırır.
np.unique(memleket) 

array(['Ankara', 'Antalya', 'İstanbul', 'İzmir'], dtype='<U8')

In [360]:
unique,counts=np.unique(memleket,return_counts=True)
print(unique)
print(counts)
dict(zip(unique,counts)) #dict sözlük olarak tanımla ve unique ve counts'u birleştir demektir

['Ankara' 'Antalya' 'İstanbul' 'İzmir']
[2 2 4 1]


{'Ankara': 2, 'Antalya': 2, 'İstanbul': 4, 'İzmir': 1}

In [364]:
frekans=np.asarray((unique,counts)).T
frekans #iç içe liste haline getirmiş olduk.

array([['Ankara', '2'],
       ['Antalya', '2'],
       ['İstanbul', '4'],
       ['İzmir', '1']], dtype='<U21')