In [ ]:
## numpy: Numeric python
sayısal Python
kurulu değilse pip install numpy diyebilirsin

In [15]:
#kütüphaneyi içe actarma
import numpy as np

In [17]:
#versiyon kontrolü
np.__version__

'1.26.4'

In [19]:
#bir numpy dizisi oluşturma
sayilar=np.array([1,2,3,4,5,6,7,8,9,10])
sayilar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#türünü kontrol et
type(sayilar)

numpy.ndarray

In [23]:
sayi_listesi=[1,2,3,4,5,6,7,8,9,10]
type(sayi_listesi)

list

In [25]:
np_sayi_listesi=np.array(list(range(1,500)))
np_sayi_listesi

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [27]:
np_sayi_listesi.dtype #veri türünü görmüş olduk. dtype özelliktir

dtype('int32')

In [36]:
#Items, veri tipinin byte cinsinden türünü verir. 32/8 1 byte 8 bit 4 byte
np_sayi_listesi.itemsize

4

In [38]:
#10 sayısının 2li sistemdeki karşılığı
bin(10)

'0b1010'

In [ ]:
#100= 0*0+0*10+1*100


In [ ]:
#1111 (2**4)-1, kolay yolu 

In [40]:
(2**4)-1

15

In [46]:
(2**5)-1

31

In [53]:
#Numpy farklı veri türlerini alabilir.
renkler=np.array(['Kırmızı','Yeşil','Mavi']) #rgb kodlama
renkler

array(['Kırmızı', 'Yeşil', 'Mavi'], dtype='<U7')

In [ ]:
#U7 unicode string demektir. 7 karakterle ifade ediliyor, kırmızı en uzun metni seçti.

In [55]:
renkler.itemsize 

28

### ascii tablosunda her bir karakter 4 bitlik ifadeyle gösterilir.

In [62]:
sayi_listesi=list(range(1,11))
np_sayi=np.array(sayi_listesi)
np_sayi #1 liste 1 boyutlu dizidir.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
#dizilerde boyutlar, dizinin boyutunu gösterir
np_sayi.ndim

1

In [74]:
np_sayi[0] #np dizisindeki birinci sayıyı getirir.

1

In [68]:
satir1=[1,2,3]
satir2=[4,5,6]
satir3=[7,8,9]
matris=np.array([satir1,satir2,satir3])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
matris.ndim 

2

In [ ]:
#boyut demek iç içe liste sayısı demektir.

In [94]:
matris[0:3] #dilimlemede bitişe kadar.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
matris[2] #index numarası verileni getir demektir.

array([7, 8, 9])

In [100]:
matris[1]

array([4, 5, 6])

In [102]:
matris_satir=matris[1]
matris_satir

array([4, 5, 6])

In [104]:
matris_satir[1]

5

In [108]:
matris[1:1]

array([], shape=(0, 3), dtype=int32)

In [112]:
matris[1][1] #satırı seç daha sonra listenin elemanını seç

5

In [116]:
matris[2][2]

9

In [120]:
#shape=satır,sütun sayısını verir
matris.shape #3 satır ve 3 sütundan oluşur.

(3, 3)

In [122]:
satir1=[1,2,3]
satir2=[4,5,6]
matris=np.array([satir1,satir2])
matris

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
matris.ndim #ndim boyut demektir.

2

In [128]:
#numpy dizi oluşturma
cift_sayi=np.arange(0,11,2) #arange bir metottur
cift_sayi

array([ 0,  2,  4,  6,  8, 10])

In [134]:
#birlerden oluşan tek boyutlu dizi oluştur
birler=np.ones(6)
birler

array([1., 1., 1., 1., 1., 1.])

In [139]:
birler_matris=np.ones((2,3))
birler_matris

array([[1., 1., 1.],
       [1., 1., 1.]])

In [141]:
#sıfırlardan oluşan örneğinin oluşturalım
sifirlar=np.zeros(6)
sifirlar

array([0., 0., 0., 0., 0., 0.])

In [143]:
sifirlar.ndim

1

In [147]:
sifirlar.shape

(6,)

In [149]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [151]:
np.eye(5).shape

(5, 5)

In [167]:
#rastgele sayılar üretelim, büyük sayılar kuralı
for i in range(1000):
    print(np.random.randint(1,101)) #0dan 5 e kadar 100 tane sayı üretir.

92
5
91
34
57
20
40
51
47
12
97
57
54
87
11
5
64
86
67
12
80
33
80
79
41
55
37
5
10
70
43
76
66
8
37
85
61
56
13
97
39
6
26
70
70
98
82
89
1
84
68
76
52
64
85
89
45
6
2
55
80
44
42
11
15
1
90
4
89
34
79
10
74
5
55
69
26
97
61
14
34
87
88
11
25
49
82
62
32
43
77
53
77
60
85
64
22
74
5
77
42
66
61
23
7
2
71
98
7
47
6
81
3
75
99
16
25
14
30
44
100
44
81
51
8
9
52
20
48
68
49
28
88
58
43
7
77
82
57
52
33
79
68
89
22
19
99
41
44
5
21
33
96
94
81
30
33
100
46
33
39
79
72
5
84
28
62
15
15
1
18
66
16
92
92
23
8
34
98
14
86
39
73
72
75
60
17
76
32
93
59
25
75
14
5
92
85
65
30
69
100
67
10
16
45
81
78
61
8
83
92
3
59
76
39
87
45
84
16
75
64
9
30
36
87
69
11
56
70
21
15
7
77
74
46
98
44
77
49
90
44
53
18
52
71
61
90
25
58
100
91
91
37
52
45
82
46
58
51
71
70
61
26
8
54
7
63
81
3
100
52
52
92
14
45
42
9
80
54
8
75
12
15
73
50
97
29
46
94
46
13
80
91
17
39
32
57
86
4
33
65
54
66
38
89
71
14
96
78
57
85
47
6
8
99
32
19
1
94
86
31
61
91
90
45
98
73
86
50
87
61
86
70
20
33
68
31
39
4
34
21
12
90
25
61

In [173]:
sayilar=np.random.randint(0,101,10) #0 dan 100 dahil 10 ssayı üretir
sayilar

array([28, 40, 44,  6, 68, 29, 27, 11,  0, 36])

In [177]:
for i in sayilar:
    print(i)

28
40
44
6
68
29
27
11
0
36


In [41]:
#şanslı kişileri seçelim
isimler=['Gülceren','İrem Zehra', 'Murat']
np.random.choice(isimler,1) #listeyi ve kaç kişi seçileceğini belirtir.

array(['İrem Zehra'], dtype='<U10')

In [43]:
#np dizisine öge ekleme
isimler=np.append(isimler,"Mustafa")
isimler

array(['Gülceren', 'İrem Zehra', 'Murat', 'Mustafa'], dtype='<U10')

In [201]:
sifir_dizi=np.zeros((3,3))
ekli_liste=np.append(sifir_dizi,[[1,2,3]], axis=0) 
sifir_dizi


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [203]:
ekli_liste

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [209]:
sifir_dizi=np.zeros((3,3))
ekli_liste=np.append(sifir_dizi,[[1,2,3]], axis=1) 
#sütün olarak bu şekilde eklenemez

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 1

In [29]:
#kodlarla ilgili poe.com
sifir_dizi=np.zeros((3, 3))
#print(sifir_dizi)
ek_sütun = np.array([1, 2, 3])
ekli_liste = np.hstack((sifir_dizi, ek_sütun.reshape(3, 1)))
print(ekli_liste)


[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


In [31]:
#sütun ekleme
sifir_dizi=np.zeros((3,3))
print(sifir_dizi)
ekli_liste=np.append(sifir_dizi, [[1],[2],[3]], axis=1)
#axis=1 dersek sütun olarak ekler
ekli_liste

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0., 1.],
       [0., 0., 0., 2.],
       [0., 0., 0., 3.]])

In [33]:
dizi1=np.array([[1,2,3]])
dizi1.ndim,dizi1.shape
#axis=0

(2, (1, 3))

In [35]:
dizi1=np.array([[1],[2],[3]])
dizi1.ndim,dizi1.shape 
#axis=1

(2, (3, 1))

In [45]:
isimler

array(['Gülceren', 'İrem Zehra', 'Murat', 'Mustafa'], dtype='<U10')

In [47]:
#öge sayısı
len(isimler)

4

In [49]:
#liste ve silinecek index sayısı
isimler=np.delete(isimler,2)
isimler

array(['Gülceren', 'İrem Zehra', 'Mustafa'], dtype='<U10')